from __future__ import annotations

import base64
import json
import re
from typing import Any

from app.models import CanonicalExtraction
from app.models.schemas import SoapNote

MEDCOPILOT_TAG_SYSTEM = "https://medcopilot.ai/fhir/tags"
MEDCOPILOT_IDENTIFIER_SYSTEM = "https://medcopilot.ai/fhir/identifiers"


class FhirMapper:
    """Map canonical extraction output to compact, readable FHIR R4 resource JSON."""

    _speaker_label_pattern = re.compile(
        r"^\s*(patient|doctor|clinician|provider|nurse|пациент|врач|доктор|клиницист|медсестра)\s*:\s*",
        flags=re.IGNORECASE,
    )
    _drop_prefixes = (
        "понимаю",
        "понятно",
        "ясно",
        "давайте",
        "опишите",
        "расскажите",
        "скажите",
        "это ",
        "как ",
        "когда ",
        "почему ",
        "скорее",
        "и началась",
        "прямая",
        "примая",
    )
    _condition_prefixes = (
        "врач считает, что ",
        "врач считает что ",
        "диагноз: ",
        "assessment: ",
        "assessment ",
        "likely ",
        "probable ",
        "possible ",
        "вероятна ",
        "вероятен ",
        "вероятно ",
        "подозрение на ",
        "подозревается ",
        "похоже на ",
        "картина соответствует ",
        "признаки ",
    )
    _symptom_like_markers = (
        "усталост",
        "сонлив",
        "сухост",
        "слабост",
        "жажд",
        "одыш",
        "боль",
    )
    _diagnosis_markers = (
        "синдром",
        "инфекц",
        "гиперт",
        "диаб",
        "астм",
        "мигр",
        "рефлюкс",
        "анеми",
        "бронх",
        "фаринг",
        "тонзилл",
        "пневмон",
        "заболев",
        "disorder",
        "disease",
    )

    def map_to_resources(
        self,
        extraction: CanonicalExtraction,
        patient_id: str,
        encounter_id: str | None = None,
        soap_note: SoapNote | None = None,
        session_id: str | None = None,
    ) -> list[dict[str, Any]]:
        resources: list[dict[str, Any]] = []

        resources.extend(self._map_conditions(extraction, patient_id, encounter_id, session_id))
        resources.extend(self._map_observations(extraction, patient_id, encounter_id, session_id))
        resources.extend(self._map_medication_statements(extraction, patient_id, encounter_id, session_id))
        resources.extend(self._map_allergies(extraction, patient_id, encounter_id, session_id))
        resources.extend(self._map_document_reference(soap_note, patient_id, encounter_id, session_id))

        return resources

    def _base_subject(self, patient_id: str) -> dict[str, str]:
        return {"reference": f"Patient/{patient_id}"}

    def _encounter_ref(self, encounter_id: str | None) -> dict[str, str] | None:
        if not encounter_id:
            return None
        return {"reference": f"Encounter/{encounter_id}"}

    def _base_metadata(self, *, session_id: str | None, resource_kind: str, ordinal: int) -> tuple[dict[str, Any], list[dict[str, str]]]:
        identifier_value = f"{session_id or 'sessionless'}:{resource_kind}:{ordinal}"
        meta = {
            "tag": [
                {
                    "system": MEDCOPILOT_TAG_SYSTEM,
                    "code": "medcopilot-generated",
                    "display": "Generated by MedCoPilot",
                }
            ]
        }
        identifiers = [{"system": MEDCOPILOT_IDENTIFIER_SYSTEM, "value": identifier_value}]
        return meta, identifiers

    def _map_conditions(
        self,
        extraction: CanonicalExtraction,
        patient_id: str,
        encounter_id: str | None,
        session_id: str | None,
    ) -> list[dict[str, Any]]:
        conditions: list[dict[str, Any]] = []

        for index, original_text in enumerate(extraction.diagnoses, start=1):
            condition_text = self._normalize_condition_text(original_text)
            if not condition_text:
                continue

            meta, identifiers = self._base_metadata(
                session_id=session_id,
                resource_kind="condition",
                ordinal=index,
            )
            resource: dict[str, Any] = {
                "resourceType": "Condition",
                "meta": meta,
                "identifier": identifiers,
                "clinicalStatus": {
                    "coding": [
                        {
                            "system": "http://terminology.hl7.org/CodeSystem/condition-clinical",
                            "code": "active",
                            "display": "Active",
                        }
                    ]
                },
                "verificationStatus": {
                    "coding": [
                        {
                            "system": "http://terminology.hl7.org/CodeSystem/condition-ver-status",
                            "code": "provisional",
                            "display": "Provisional",
                        }
                    ]
                },
                "category": [
                    {
                        "coding": [
                            {
                                "system": "http://terminology.hl7.org/CodeSystem/condition-category",
                                "code": "encounter-diagnosis",
                                "display": "Encounter Diagnosis",
                            }
                        ],
                        "text": "Диагноз консультации",
                    }
                ],
                "subject": self._base_subject(patient_id),
                "code": {"text": condition_text},
            }
            encounter_ref = self._encounter_ref(encounter_id)
            if encounter_ref:
                resource["encounter"] = encounter_ref
            if self._clean_text(original_text) != condition_text:
                resource["note"] = [{"text": self._clean_text(original_text)}]
            conditions.append(resource)

        return conditions

    def _map_observations(
        self,
        extraction: CanonicalExtraction,
        patient_id: str,
        encounter_id: str | None,
        session_id: str | None,
    ) -> list[dict[str, Any]]:
        observations: list[dict[str, Any]] = []
        observation_items = [
            ("Пациент сообщает о симптоме", text)
            for text in extraction.symptoms
        ]
        observation_items.extend(("Клиническое наблюдение", text) for text in extraction.observations)
        observation_items.extend((self._measurement_label(text), text) for text in extraction.measurements)

        for index, (label, text) in enumerate(observation_items, start=1):
            clean_text = self._clean_text(text)
            if not clean_text:
                continue

            meta, identifiers = self._base_metadata(
                session_id=session_id,
                resource_kind="observation",
                ordinal=index,
            )
            resource: dict[str, Any] = {
                "resourceType": "Observation",
                "meta": meta,
                "identifier": identifiers,
                "status": "final",
                "category": [{"text": "Клиническое наблюдение"}],
                "subject": self._base_subject(patient_id),
                "code": {"text": label},
                "valueString": clean_text,
            }
            encounter_ref = self._encounter_ref(encounter_id)
            if encounter_ref:
                resource["encounter"] = encounter_ref
            observations.append(resource)

        return observations

    def _map_medication_statements(
        self,
        extraction: CanonicalExtraction,
        patient_id: str,
        encounter_id: str | None,
        session_id: str | None,
    ) -> list[dict[str, Any]]:
        medications: list[dict[str, Any]] = []

        for index, text in enumerate(extraction.medications, start=1):
            clean_text = self._clean_text(text)
            if not clean_text:
                continue

            meta, identifiers = self._base_metadata(
                session_id=session_id,
                resource_kind="medication",
                ordinal=index,
            )
            resource: dict[str, Any] = {
                "resourceType": "MedicationStatement",
                "meta": meta,
                "identifier": identifiers,
                "status": "active",
                "subject": self._base_subject(patient_id),
                "medicationCodeableConcept": {"text": clean_text},
            }
            encounter_ref = self._encounter_ref(encounter_id)
            if encounter_ref:
                resource["context"] = encounter_ref
            medications.append(resource)

        return medications

    def _map_allergies(
        self,
        extraction: CanonicalExtraction,
        patient_id: str,
        encounter_id: str | None,
        session_id: str | None,
    ) -> list[dict[str, Any]]:
        allergies: list[dict[str, Any]] = []

        for index, text in enumerate(extraction.allergies, start=1):
            clean_text = self._clean_text(text)
            if not clean_text:
                continue

            meta, identifiers = self._base_metadata(
                session_id=session_id,
                resource_kind="allergy",
                ordinal=index,
            )
            resource: dict[str, Any] = {
                "resourceType": "AllergyIntolerance",
                "meta": meta,
                "identifier": identifiers,
                "patient": self._base_subject(patient_id),
                "code": {"text": clean_text},
            }
            encounter_ref = self._encounter_ref(encounter_id)
            if encounter_ref:
                resource["encounter"] = encounter_ref
            allergies.append(resource)

        return allergies

    def _map_document_reference(
        self,
        soap_note: SoapNote | None,
        patient_id: str,
        encounter_id: str | None,
        session_id: str | None,
    ) -> list[dict[str, Any]]:
        if soap_note is None:
            return []

        meta, identifiers = self._base_metadata(
            session_id=session_id,
            resource_kind="document-reference",
            ordinal=1,
        )
        attachment_data = base64.b64encode(
            json.dumps(soap_note.model_dump(mode="json"), ensure_ascii=False).encode("utf-8")
        ).decode("ascii")
        soap_summary = self._build_soap_summary(soap_note)
        resource: dict[str, Any] = {
            "resourceType": "DocumentReference",
            "meta": meta,
            "identifier": identifiers,
            "status": "current",
            "subject": self._base_subject(patient_id),
            "type": {"text": "SOAP-заметка консультации"},
            "description": (
                "Полная структурированная SOAP-заметка консультации в JSON. "
                f"{soap_summary}"
            ),
            "content": [
                {
                    "attachment": {
                        "contentType": "application/json",
                        "title": f"SOAP-заметка {session_id or patient_id}",
                        "data": attachment_data,
                    }
                }
            ],
        }
        encounter_ref = self._encounter_ref(encounter_id)
        if encounter_ref:
            resource["context"] = {"encounter": [encounter_ref]}
        return [resource]

    def _normalize_condition_text(self, text: str) -> str | None:
        cleaned = self._clean_text(text)
        if not cleaned or "?" in cleaned:
            return None

        normalized = cleaned.casefold()
        if any(normalized.startswith(prefix) for prefix in self._drop_prefixes):
            return None

        candidate = cleaned
        normalized_candidate = normalized
        for prefix in self._condition_prefixes:
            if normalized_candidate.startswith(prefix):
                candidate = cleaned[len(prefix) :].strip(" ,.-:")
                normalized_candidate = candidate.casefold()
                break

        if not candidate:
            return None
        if any(normalized_candidate.startswith(prefix) for prefix in self._drop_prefixes):
            return None
        if len(candidate.split()) > 7 or len(candidate) > 80:
            return None
        if any(marker in normalized_candidate for marker in self._symptom_like_markers) and not any(
            marker in normalized_candidate for marker in self._diagnosis_markers
        ):
            return None
        return candidate[0].upper() + candidate[1:] if len(candidate) > 1 else candidate.upper()

    def _measurement_label(self, text: str) -> str:
        normalized = text.casefold()
        if "мм рт" in normalized or "mmhg" in normalized or "/" in normalized:
            return "Артериальное давление"
        if "глюкоз" in normalized or "glucose" in normalized:
            return "Глюкоза"
        if "температур" in normalized or "°c" in normalized or "temperature" in normalized:
            return "Температура тела"
        if "сатурац" in normalized or "spo2" in normalized or "oxygen" in normalized:
            return "Сатурация кислорода"
        if "пульс" in normalized or "heart rate" in normalized or "чсс" in normalized:
            return "Частота сердечных сокращений"
        if "вес" in normalized or "kg" in normalized or "кг" in normalized:
            return "Масса тела"
        return "Измерение"

    def _clean_text(self, text: str) -> str:
        without_speaker = self._speaker_label_pattern.sub("", str(text))
        return re.sub(r"\s+", " ", without_speaker).strip(" \t\r\n-:.")

    @staticmethod
    def _build_soap_summary(soap_note: SoapNote) -> str:
        return (
            "Содержит разделы: "
            f"субъективно {len(soap_note.subjective.reported_symptoms) + len(soap_note.subjective.reported_concerns)}, "
            f"объективно {len(soap_note.objective.observations) + len(soap_note.objective.measurements)}, "
            f"оценка {len(soap_note.assessment.diagnoses) + len(soap_note.assessment.evaluation)}, "
            f"план {len(soap_note.plan.treatment) + len(soap_note.plan.follow_up_instructions)}."
        )
